
INSERT INTO picks VALUES (1, 29);  # eagles (win)
INSERT INTO picks VALUES (2, 27);  # 49ers (loss)
INSERT INTO picks VALUES (3, 22);  # saints (win)
INSERT INTO picks VALUES (4, 10);  # chargers (win)
INSERT INTO picks VALUES (5, 26);  # seahawks (win)
INSERT INTO picks VALUES (6, 9);   # broncos (win)
INSERT INTO picks VALUES (7, 4);   # ravens (win)
INSERT INTO picks VALUES (8, 11);  # chiefs (win)
INSERT INTO picks VALUES (9, 1);   # bengals (win)
INSERT INTO picks VALUES (10, 30); # cowboys (win)
INSERT INTO picks VALUES (11, 25); # cardinals (win)
INSERT INTO picks VALUES (12, 5);  # colts (win)
INSERT INTO picks VALUES (13, 14); # dolphins (win)
INSERT INTO picks VALUES (14, 18); # lions (win)
INSERT INTO picks VALUES (15, 31); # giants (win)
INSERT INTO picks VALUES (16, 17); # packers (win)

